In [55]:
import pandas as pd

In [56]:
demographics_df = pd.read_csv('Demographics_Data.csv', index_col=0)
blood_pressure_df = pd.read_csv('Blood_Pressure_Examination_Data.csv', index_col=0)
body_measures_df = pd.read_csv('Body_Measures_Examination_Data.csv', index_col=0)
alcohol_df = pd.read_csv('Alcohol_Use_Questionnaire_Data.csv', index_col=0)
blood_pressure_cholestrol_df = pd.read_csv('Blood_Pressure_Cholestrol_Questionnaire_Data.csv', index_col=0)
consumer_behavior_df = pd.read_csv('Consumer_Behavior_Questionnaire_Data.csv', index_col=0)
diabetes_df = pd.read_csv('Diabetes_Questionnaire_Data.csv', index_col=0)
diet_behavior_nutrition_df = pd.read_csv('Diet_Behavior_Nutrition_Questionnaire_Data.csv', index_col=0)
medical_conditions_df = pd.read_csv('Medical_Conditions_Questionnaire_Data.csv', index_col=0)
physical_activity_df = pd.read_csv('Physical_Activity_Questionnaire_Data.csv', index_col=0)
smoking_df = pd.read_csv('Smoking_Questionnaire_Data.csv', index_col=0)
target_df = pd.read_csv('Target.csv', index_col=0)

In [57]:
print(demographics_df.shape)
print(blood_pressure_df.shape)
print(body_measures_df.shape)
print(alcohol_df.shape)
print(blood_pressure_cholestrol_df.shape)
print(consumer_behavior_df.shape)
print(diabetes_df.shape)
print(diet_behavior_nutrition_df.shape)
print(medical_conditions_df.shape)
print(physical_activity_df.shape)
print(smoking_df.shape)
print(target_df.shape)

(9971, 6)
(9544, 5)
(9544, 5)
(5735, 3)
(6327, 3)
(9971, 5)
(9575, 2)
(9971, 5)
(9575, 6)
(9255, 4)
(7001, 3)
(9575, 2)

In [58]:
master_raw = pd.merge(demographics_df, blood_pressure_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, body_measures_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, alcohol_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, blood_pressure_cholestrol_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, consumer_behavior_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, diabetes_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, diet_behavior_nutrition_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, medical_conditions_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, physical_activity_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, smoking_df, on='SEQN', how='left')
master_raw = pd.merge(master_raw, target_df, on='SEQN', how='left')

In [59]:
master_raw.head()

,SEQN,Gender,Age,Race,Country_Born,Family_Income,Heart_Rate,Pulse_Regular_Irregular,Systolic_BP_Avg,Diastolic_BP_Avg,...,Doctor_told_you_lose_weight,Doctor_told_you_exercise,Doctor_told_you_reduce_salt,Doctor_told_you_reduce_fat_calories,Walk_or_bicycle,Vigorous_recreational_activities,Moderate_recreational_activities,Smoked_at_least_100_cigarettes_in_life,Do_you_now_smoke_cigarettes,Target
0,83732.0,1.0,62.0,3.0,1.0,10.0,76.0,1.0,122.666667,65.333333,...,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0
1,83733.0,1.0,53.0,3.0,2.0,4.0,72.0,1.0,140.000000,86.000000,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0
2,83734.0,1.0,78.0,3.0,1.0,5.0,56.0,1.0,135.333333,45.333333,...,2.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,3.0,2.0
3,83735.0,2.0,56.0,3.0,1.0,10.0,78.0,1.0,134.000000,70.000000,...,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0
4,83736.0,2.0,42.0,4.0,1.0,7.0,76.0,1.0,104.000000,60.000000,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0

In [61]:
master_raw.shape

(9971, 38)

In [62]:
master_data = master_raw[(master_raw['Age']>=18) & (master_raw['Age']<66)]

In [63]:
master_data.shape

(4707, 38)

In [64]:
master_data.head()

,SEQN,Gender,Age,Race,Country_Born,Family_Income,Heart_Rate,Pulse_Regular_Irregular,Systolic_BP_Avg,Diastolic_BP_Avg,...,Doctor_told_you_lose_weight,Doctor_told_you_exercise,Doctor_told_you_reduce_salt,Doctor_told_you_reduce_fat_calories,Walk_or_bicycle,Vigorous_recreational_activities,Moderate_recreational_activities,Smoked_at_least_100_cigarettes_in_life,Do_you_now_smoke_cigarettes,Target
0,83732.0,1.0,62.0,3.0,1.0,10.0,76.0,1.0,122.666667,65.333333,...,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,2.0
1,83733.0,1.0,53.0,3.0,2.0,4.0,72.0,1.0,140.000000,86.000000,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0
3,83735.0,2.0,56.0,3.0,1.0,10.0,78.0,1.0,134.000000,70.000000,...,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0
4,83736.0,2.0,42.0,4.0,1.0,7.0,76.0,1.0,104.000000,60.000000,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0
9,83741.0,1.0,22.0,4.0,1.0,7.0,66.0,1.0,111.333333,72.666667,...,2.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0

In [65]:
master_data.isna().sum()

SEQN                                           0
Gender                                         0
Age                                            0
Race                                           0
Country_Born                                   1
Family_Income                                328
Heart_Rate                                   318
Pulse_Regular_Irregular                      318
Systolic_BP_Avg                              321
Diastolic_BP_Avg                             321
Weight_kg                                    229
Height_cm                                    229
BMI                                          233
Waist_cm                                     402
Avg_Num_Alcohol_Drink_a_Day                 1903
Have_4_5_Plus_Drinks_a_Day                  1393
Ever_told_high_blood_pressure                  3
Ever_told_high_cholesterol                    23
Money_spent_at_supermarket_grocery_store     227
Money_spent_on_food_at_other_stores          224
Money_spent_eating_out                       317
Money_spent_carryout_delivered_foods         247
Doctor_told_you_have_diabetes                  3
Past_30day_milk_consumption                    0
Meals_not_home_prepared                        6
Past_30day_ready_to_eat_foods                 21
Past_30day_frozen_meals_pizza                  7
Doctor_told_you_overweight                     3
Doctor_told_you_lose_weight                    0
Doctor_told_you_exercise                       2
Doctor_told_you_reduce_salt                    5
Doctor_told_you_reduce_fat_calories            4
Walk_or_bicycle                                1
Vigorous_recreational_activities               1
Moderate_recreational_activities               2
Smoked_at_least_100_cigarettes_in_life         5
Do_you_now_smoke_cigarettes                 2931
Target                                       284
dtype: int64

In [66]:
master_data.to_csv('Master_Data.csv')